[start]
cmd = "bash /app/deploy/start.sh"

[setup]
nixPkgs = [
    "(php83.withExtensions (pe: pe.enabled ++ [ pe.pdo_mysql ]))",
    "nginx",
    "php83Packages.composer",
    "nodejs_22",
    "npm-9_x"
]
nixLibs = []
nixOverlays = ["https://github.com/railwayapp/nix-npm-overlay/archive/main.tar.gz"]
nixpkgsArchive = "e24b4c09e963677b1beea49d411cd315a024ad3a"
aptPkgs = ["curl", "wget"]
